// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tempic.Data;

#nullable disable

namespace Tempic.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250518232538_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Tempic.Models.ImageMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpirationDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinioBucketName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinioObjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UniqueLinkId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDateUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UniqueLinkId")
                        .IsUnique();

                    b.ToTable("ImageMetadatas");
                });
#pragma warning restore 612, 618
        }
    }
}
